CREATE DATABASE ssm;
USE SSM;

DROP TABLE IF EXISTS T_ROLE;

CREATE TABLE T_ROLE (
  ID        BIGINT PRIMARY KEY AUTO_INCREMENT NOT NULL,
  ROLE_NAME VARCHAR(36)                       NOT NULL,
  NOTE      VARCHAR(36) DEFAULT ''
);

INSERT INTO T_ROLE (ID, ROLE_NAME, NOTE)
VALUES
  (0, 'admin', ''),
  (1, 'account', 'first user');

INSERT INTO T_ROLE (ROLE_NAME, NOTE) VALUES
  ('ROLE_NAME', 'd');